---
- name: Install FTP and UWF
  apt:
    name: {{ item }}
    state: present 
    update_cache: true
  loop: 
    - vsftpd
    - ufw 

- name: Check status vsftpd
  command: systemctl status vsftpd
  register: result 
  ignore_errors: true

- name: Show status vsftpd
  debug:
    var: result 

- name: Add user FTP
  user:
    name: ftp_user
    uid: 1040
    comment: ftp user 
    group: sudo 

- name: add user to conf ftp 
  lineinfile:
    dest: /etc/vsftpd.userlist
    line: ftp_user
    state: present 
    create: true 

- name:  Create directory with persistens 
  file:
   path: /home/ftp_user/ftp_dir 
   owner: ftp_user
   mode: 750
